# IMPORTS_FRANK

In [1]:
import pandas as pd

In [2]:
countries = pd.read_csv('../raw_data/CountryCodes.csv', encoding = 'unicode_escape')
countries.dropna(inplace=True)
countries.head()

          Country Alpha_2_code Alpha_3_code  Numeric
0     Afghanistan           AF          AFG      4.0
1         Albania           AL          ALB      8.0
2         Algeria           DZ          DZA     12.0
3  American Samoa           AS          ASM     16.0
4         Andorra           AD          AND     20.0

In [3]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 247 entries, 0 to 248
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       247 non-null    object
 1   Alpha_2_code  247 non-null    object
 2   Alpha_3_code  247 non-null    object
 3   Numeric       247 non-null    float64
dtypes: float64(1), object(3)
memory usage: 9.6+ KB

Check Alpha 2 code values

In [4]:
countries[countries['Alpha_2_code'].isnull()==True]

Empty DataFrame
Columns: [Country, Alpha_2_code, Alpha_3_code, Numeric]
Index: []

## EU Countries Dictionary

In [5]:
EU_countries = pd.DataFrame.from_dict([{'Belgium': 'BE', 'Bulgaria': 'BG', 'Czechia': 'CZ', 'Denmark': 'DK', 'Germany': 'DE', 'Estonia': 'EE', 'Ireland': 'IE', 'Greece': 'EL',
                'Spain': 'ES', 'France': 'FR', 'Croatia': 'HR', 'Italy': 'IT', 'Cyprus': 'CY', 'Latvia': 'LV', 'Lithuania': 'LT', 'Luxembourg': 'LU', 
                'Hungary': 'HU', 'Malta': 'MT', 'Netherlands': 'NL', 'Austria': 'AT', 'Poland': 'PL', 'Portugal': 'PT', 'Romania': 'RO', 'Slovenia': 'SI',
                'Slovakia': 'SK', 'Finland': 'FI', 'Sweden': 'SE'}])
EU_countries = EU_countries.T.reset_index()
EU_countries.rename(columns={'index': 'EU_country', 0: 'Alpha_2_code'}, inplace=True)
EU_countries

     EU_country Alpha_2_code
0       Belgium           BE
1      Bulgaria           BG
2       Czechia           CZ
3       Denmark           DK
4       Germany           DE
5       Estonia           EE
6       Ireland           IE
7        Greece           EL
8         Spain           ES
9        France           FR
10      Croatia           HR
11        Italy           IT
12       Cyprus           CY
13       Latvia           LV
14    Lithuania           LT
15   Luxembourg           LU
16      Hungary           HU
17        Malta           MT
18  Netherlands           NL
19      Austria           AT
20       Poland           PL
21     Portugal           PT
22      Romania           RO
23     Slovenia           SI
24     Slovakia           SK
25      Finland           FI
26       Sweden           SE

## Imports by Country

Electric Imports by Partner Country

In [6]:
imports = pd.read_csv('../raw_data/ElecImportsByPartnerCountry.csv', encoding = 'unicode_escape')
imports.head()

,freq,siec,partner,unit,Alpha_2_code,1990,1991,1992,1993,1994,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,A,E7000,AD,GWH,AL,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
1,A,E7000,AD,GWH,AT,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
2,A,E7000,AD,GWH,BA,:,:,:,:,:,...,:,:,:,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,A,E7000,AD,GWH,BE,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,A,E7000,AD,GWH,BG,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [7]:
imports['Alpha_2_code'].unique()

array(['AL', 'AT', 'BA', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EA19', 'EE',
       'EL', 'ES', 'EU27_2020', 'FI', 'FR', 'GE', 'HR', 'HU', 'IE', 'IS',
       'IT', 'LI', 'LT', 'LU', 'LV', 'MD', 'ME', 'MK', 'MT', 'NL', 'NO',
       'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'TR', 'UA', 'UK', 'XK'],
      dtype=object)

In [8]:
imports_CZ = imports.query("Alpha_2_code == 'CZ'")

In [9]:
imports_CZ.query("partner == 'AT'")

,freq,siec,partner,unit,Alpha_2_code,1990,1991,1992,1993,1994,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
436,A,E7000,AT,GWH,CZ,34000,221000,216000,201000,18000,...,0.000,0.000,0.000,265000.0,41000.0,136000,62478,112561,144762,378420
7531,A,H8000,AT,TJ,CZ,0.000,0.000,0.000,0.000,0.000,...,17000,17000,32000,27000.0,29000.0,33000,52503,51639,46427,47351

In [10]:
imports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14190 entries, 0 to 14189
Data columns (total 36 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   freq          14190 non-null  object
 1   siec          14190 non-null  object
 2   partner       14104 non-null  object
 3   unit          14190 non-null  object
 4   Alpha_2_code  14190 non-null  object
 5   1990          14190 non-null  object
 6   1991          14190 non-null  object
 7   1992          14190 non-null  object
 8   1993          14190 non-null  object
 9   1994          14190 non-null  object
 10  1995          14190 non-null  object
 11  1996          14190 non-null  object
 12  1997          14190 non-null  object
 13  1998          14190 non-null  object
 14  1999          14190 non-null  object
 15  2000          14190 non-null  object
 16  2001          14190 non-null  object
 17  2002          14190 non-null  object
 18  2003          14190 non-null  object
 19  2004          14190 non-null  object
 20  2005          14190 non-null  object
 21  2006          14190 non-null  object
 22  2007          14190 non-null  object
 23  2008          14190 non-null  object
 24  2009          14190 non-null  object
 25  2010          14190 non-null  object
 26  2011          14190 non-null  object
 27  2012          14190 non-null  object
 28  2013          14190 non-null  object
 29  2014          14190 non-null  float64
 30  2015          14190 non-null  float64
 31  2016          14190 non-null  object
 32  2017          14190 non-null  object
 33  2018          14190 non-null  object
 34  2019          14190 non-null  object
 35  2020          14190 non-null  object
dtypes: float64(2), object(34)
memory usage: 3.9+ MB

In [11]:
# check Alpha 2 code
imports[imports['Alpha_2_code'].isnull()==True]

Empty DataFrame
Columns: [freq, siec, partner, unit, Alpha_2_code, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]
Index: []

[0 rows x 36 columns]

In [12]:
# check unique values in 'siec' column
imports['siec'].unique()

array(['E7000', 'H8000'], dtype=object)

In [13]:
# merge imports df with countries df
imports = imports.merge(countries, on='Alpha_2_code', how='left')

# create new column 'EU?' and fill with True/False based on whether country is in EU dictionary
imports['EU?'] = imports['Alpha_2_code'].isin(EU_countries['Alpha_2_code'])
imports

,freq,siec,partner,unit,Alpha_2_code,1990,1991,1992,1993,1994,...,2015,2016,2017,2018,2019,2020,Country,Alpha_3_code,Numeric,EU?
0,A,E7000,AD,GWH,AL,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Albania,ALB,8.0,False
1,A,E7000,AD,GWH,AT,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Austria,AUT,40.0,True
2,A,E7000,AD,GWH,BA,:,:,:,:,:,...,0.0,0.000,0.000,0.000,0.000,0.000,Bosnia and Herzegovina,BIH,70.0,False
3,A,E7000,AD,GWH,BE,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Belgium,BEL,56.0,True
4,A,E7000,AD,GWH,BG,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Bulgaria,BGR,100.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14185,A,H8000,ZA,TJ,SK,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Slovakia,SVK,703.0,True
14186,A,H8000,ZA,TJ,TR,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Turkey,TUR,792.0,False
14187,A,H8000,ZA,TJ,UA,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,0.000,Ukraine,UKR,804.0,False
14188,A,H8000,ZA,TJ,UK,0.000,0.000,0.000,0.000,0.000,...,0.0,0.000,0.000,0.000,0.000,:,NaN,NaN,NaN,False
14189,A,H8000,ZA,TJ,XK,:,:,:,:,:,...,0.0,0.000,0.000,0.000,0.000,0.000,NaN,NaN,NaN,False

In [14]:
# rename Alpha 2 code in countries df to 'Partner_country'
countries.rename({'Alpha_2_code': 'partner'}, axis=1, inplace=True)
countries

            Country partner Alpha_3_code  Numeric
0       Afghanistan      AF          AFG      4.0
1           Albania      AL          ALB      8.0
2           Algeria      DZ          DZA     12.0
3    American Samoa      AS          ASM     16.0
4           Andorra      AD          AND     20.0
..              ...     ...          ...      ...
244  Western Sahara      EH          ESH    732.0
245           Yemen      YE          YEM    887.0
246          Zambia      ZM          ZMB    894.0
247        Zimbabwe      ZW          ZWE    716.0
248  Ã
land Islands      AX          ALA    248.0

[247 rows x 4 columns]

In [15]:
# create new df EU_imports by merging imports and countries to get the name of the partner countries
EU_imports = imports.merge(countries, on='partner', how='left')
EU_imports

,freq,siec,partner,unit,Alpha_2_code,1990,1991,1992,1993,1994,...,2018,2019,2020,Country_x,Alpha_3_code_x,Numeric_x,EU?,Country_y,Alpha_3_code_y,Numeric_y
0,A,E7000,AD,GWH,AL,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Albania,ALB,8.0,False,Andorra,AND,20.0
1,A,E7000,AD,GWH,AT,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Austria,AUT,40.0,True,Andorra,AND,20.0
2,A,E7000,AD,GWH,BA,:,:,:,:,:,...,0.000,0.000,0.000,Bosnia and Herzegovina,BIH,70.0,False,Andorra,AND,20.0
3,A,E7000,AD,GWH,BE,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Belgium,BEL,56.0,True,Andorra,AND,20.0
4,A,E7000,AD,GWH,BG,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Bulgaria,BGR,100.0,True,Andorra,AND,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14185,A,H8000,ZA,TJ,SK,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Slovakia,SVK,703.0,True,South Africa,ZAF,710.0
14186,A,H8000,ZA,TJ,TR,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Turkey,TUR,792.0,False,South Africa,ZAF,710.0
14187,A,H8000,ZA,TJ,UA,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,Ukraine,UKR,804.0,False,South Africa,ZAF,710.0
14188,A,H8000,ZA,TJ,UK,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,:,NaN,NaN,NaN,False,South Africa,ZAF,710.0
14189,A,H8000,ZA,TJ,XK,:,:,:,:,:,...,0.000,0.000,0.000,NaN,NaN,NaN,False,South Africa,ZAF,710.0

In [16]:
# rearrange columns
EU_imports.columns

Index(['freq', 'siec', 'partner', 'unit', 'Alpha_2_code', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', 'Country_x', 'Alpha_3_code_x', 'Numeric_x', 'EU?',
       'Country_y', 'Alpha_3_code_y', 'Numeric_y'],
      dtype='object')

In [17]:
EU_imports = EU_imports[['Alpha_2_code', 'Country_x', 'EU?', 'partner', 'Country_y', 'siec', 'unit',
                         '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
                         '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
                         '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
                         '2017', '2018', '2019', '2020']]
EU_imports

,Alpha_2_code,Country_x,EU?,partner,Country_y,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AL,Albania,False,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
1,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
2,BA,Bosnia and Herzegovina,False,AD,Andorra,E7000,GWH,:,:,:,...,:,:,:,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14185,SK,Slovakia,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14186,TR,Turkey,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14187,UA,Ukraine,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14188,UK,NaN,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,:
14189,XK,NaN,False,ZA,South Africa,H8000,TJ,:,:,:,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [18]:
EU_imports.rename({'Country_x': 'Country', 'Country_y': 'Partner_country'}, axis=1, inplace=True)
EU_imports

/Users/frankpeluso/.pyenv/versions/3.8.12/envs/lewagon/lib/python3.8/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AL,Albania,False,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
1,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
2,BA,Bosnia and Herzegovina,False,AD,Andorra,E7000,GWH,:,:,:,...,:,:,:,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14185,SK,Slovakia,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14186,TR,Turkey,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14187,UA,Ukraine,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14188,UK,NaN,False,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,:
14189,XK,NaN,False,ZA,South Africa,H8000,TJ,:,:,:,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [19]:
# Filter out non-EU importing countries
EU_imports_filtered = EU_imports[EU_imports['EU?'] == True]
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
5,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
6,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14180,PT,Portugal,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14181,RO,Romania,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14183,SE,Sweden,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14184,SI,Slovenia,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
14185,SK,Slovakia,True,ZA,South Africa,H8000,TJ,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [20]:
EU_imports_filtered = EU_imports_filtered[EU_imports_filtered['siec'] == 'E7000']
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
5,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
6,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7085,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7086,RO,Romania,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7088,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7089,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7090,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [21]:
EU_imports_filtered = EU_imports_filtered[EU_imports_filtered['unit'] == 'GWH']
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
5,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
6,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7085,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7086,RO,Romania,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7088,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7089,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
7090,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [22]:
EU_imports_filtered['Country'].unique()

array(['Austria', 'Belgium', 'Bulgaria', 'Cyprus', 'Czechia', 'Germany',
       'Denmark', 'Estonia', 'Greece', 'Spain', 'Finland', 'France',
       'Croatia', 'Hungary', 'Ireland', 'Italy', 'Lithuania',
       'Luxembourg', 'Latvia', 'Malta', 'Netherlands (the)', 'Poland',
       'Portugal', 'Romania', 'Sweden', 'Slovenia', 'Slovakia'],
      dtype=object)

In [23]:
EU_imports_filtered['Partner_country'].unique()

array(['Andorra', 'United Arab Emirates (the)', nan, 'Albania', 'Armenia',
       'Angola', 'Argentina', 'Austria', 'Australia', 'Aruba',
       'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh',
       'Belgium', 'Bulgaria', 'Bahrain', 'Benin', 'Brunei Darussalam',
       'Bolivia (Plurinational State of)', 'Brazil', 'Bahamas (the)',
       'Belarus', 'Belize', 'Canada',
       'Congo (the Democratic Republic of the)', 'Congo (the)',
       'Switzerland', "CÃ´te d'Ivoire", 'Chile', 'Cameroon', 'China',
       'Colombia', 'Costa Rica', 'Cuba', 'Cabo Verde', 'CuraÃ§ao',
       'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Denmark',
       'Dominican Republic (the)', 'Algeria', 'Ecuador', 'Estonia',
       'Egypt', 'Greece', 'Eritrea', 'Spain', 'Ethiopia', 'Finland',
       'France', 'Gabon', 'Georgia', 'Ghana', 'Gibraltar',
       'Equatorial Guinea', 'Guatemala', 'Guinea-Bissau', 'Hong Kong',
       'Honduras', 'Croatia', 'Hungary', 'Ireland', 'Israel', 'India',
       'Iraq', 'Iran (Islamic Republic of)', 'Iceland', 'Italy',
       'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia',
       "Korea (the Democratic People's Republic of)",
       'Korea (the Republic of)', 'Kuwait', 'Kazakhstan',
       "Lao People's Democratic Republic (the)", 'Lebanon',
       'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lithuania', 'Luxembourg',
       'Latvia', 'Libya', 'Morocco', 'Moldova (the Republic of)',
       'Montenegro', 'Madagascar', 'Marshall Islands (the)',
       'Republic of North Macedonia', 'Myanmar', 'Mongolia', 'Mauritania',
       'Malta', 'Mauritius', 'Mexico', 'Malaysia', 'Mozambique',
       'New Caledonia', 'Niger (the)', 'Nigeria', 'Netherlands (the)',
       'Norway', 'Nepal', 'New Zealand', 'Oman', 'Panama', 'Peru',
       'Papua New Guinea', 'Philippines (the)', 'Pakistan', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Serbia',
       'Russian Federation (the)', 'Saudi Arabia', 'Sudan (the)',
       'Sweden', 'Singapore', 'Slovenia', 'Slovakia', 'Sierra Leone',
       'Senegal', 'South Sudan', 'Sao Tome and Principe',
       'Syrian Arab Republic', 'Togo', 'Thailand', 'Tajikistan',
       'Timor-Leste', 'Turkmenistan', 'Tunisia', 'Turkey',
       'Trinidad and Tobago', 'Taiwan (Province of China)', 'Tanzania',
       'Ukraine', 'Uganda', 'United States of America (the)', 'Uruguay',
       'Uzbekistan', 'Venezuela (Bolivarian Republic of)',
       'Virgin Islands (British)', 'Viet Nam', 'Yemen', 'South Africa'],
      dtype=object)

In [24]:
EU_imports_filtered.reset_index(drop=True, inplace=True)
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AT,Austria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
1,BE,Belgium,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
2,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
3,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4451,RO,Romania,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4452,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4453,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
4454,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.000,0.000,0.000,...,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000

In [25]:
EU_imports_filtered.dtypes

Alpha_2_code        object
Country             object
EU?                   bool
partner             object
Partner_country     object
siec                object
unit                object
1990                object
1991                object
1992                object
1993                object
1994                object
1995                object
1996                object
1997                object
1998                object
1999                object
2000                object
2001                object
2002                object
2003                object
2004                object
2005                object
2006                object
2007                object
2008                object
2009                object
2010                object
2011                object
2012                object
2013                object
2014               float64
2015               float64
2016                object
2017                object
2018                object
2019                object
2020                object
dtype: object

In [26]:
EU_imports_filtered.columns

Index(['Alpha_2_code', 'Country', 'EU?', 'partner', 'Partner_country', 'siec',
       'unit', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020'],
      dtype='object')

In [27]:
years_columns_type = {'1990': float, '1991': float, '1992': float, '1993': float, '1994': float,
                      '1995': float, '1996': float, '1997': float, '1998': float, '1999': float,
                      '2000': float, '2001': float, '2002': float, '2003': float, '2004': float,
                      '2005': float, '2006': float, '2007': float, '2008': float, '2009': float,
                      '2010': float, '2011': float, '2012': float, '2013': float, '2014': float,
                      '2015': float, '2016': float, '2017': float, '2018': float, '2019': float,
                      '2020': float}
EU_imports_filtered = EU_imports_filtered.astype(years_columns_type)
EU_imports_filtered.dtypes

Alpha_2_code        object
Country             object
EU?                   bool
partner             object
Partner_country     object
siec                object
unit                object
1990               float64
1991               float64
1992               float64
1993               float64
1994               float64
1995               float64
1996               float64
1997               float64
1998               float64
1999               float64
2000               float64
2001               float64
2002               float64
2003               float64
2004               float64
2005               float64
2006               float64
2007               float64
2008               float64
2009               float64
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
dtype: object

In [28]:
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AT,Austria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
# group df by country
EU_imports_grouped = EU_imports_filtered
EU_imports_grouped

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AT,Austria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
Group = EU_imports_grouped.groupby(['Country', 'Partner_country'])
Group.first()

                                           Alpha_2_code   EU? partner   siec  \
Country Partner_country
Austria Albania                                      AT  True      AL  E7000
        Algeria                                      AT  True      DZ  E7000
        Andorra                                      AT  True      AD  E7000
        Angola                                       AT  True      AO  E7000
        Argentina                                    AT  True      AR  E7000
...                                                 ...   ...     ...    ...
Sweden  Uzbekistan                                   SE  True      UZ  E7000
        Venezuela (Bolivarian Republic of)           SE  True      VE  E7000
        Viet Nam                                     SE  True      VN  E7000
        Virgin Islands (British)                     SE  True      VG  E7000
        Yemen                                        SE  True      YE  E7000

                                           unit  1990  1991  1992  1993  1994  \
Country Partner_country
Austria Albania                             GWH   0.0   0.0   0.0   0.0   0.0
        Algeria                             GWH   0.0   0.0   0.0   0.0   0.0
        Andorra                             GWH   0.0   0.0   0.0   0.0   0.0
        Angola                              GWH   0.0   0.0   0.0   0.0   0.0
        Argentina                           GWH   0.0   0.0   0.0   0.0   0.0
...                                         ...   ...   ...   ...   ...   ...
Sweden  Uzbekistan                          GWH   0.0   0.0   0.0   0.0   0.0
        Venezuela (Bolivarian Republic of)  GWH   0.0   0.0   0.0   0.0   0.0
        Viet Nam                            GWH   0.0   0.0   0.0   0.0   0.0
        Virgin Islands (British)            GWH   0.0   0.0   0.0   0.0   0.0
        Yemen                               GWH   0.0   0.0   0.0   0.0   0.0

                                            ...  2011  2012  2013  2014  2015  \
Country Partner_country                     ...
Austria Albania                             ...   0.0   0.0   0.0   0.0   0.0
        Algeria                             ...   0.0   0.0   0.0   0.0   0.0
        Andorra                             ...   0.0   0.0   0.0   0.0   0.0
        Angola                              ...   0.0   0.0   0.0   0.0   0.0
        Argentina                           ...   0.0   0.0   0.0   0.0   0.0
...                                         ...   ...   ...   ...   ...   ...
Sweden  Uzbekistan                          ...   0.0   0.0   0.0   0.0   0.0
        Venezuela (Bolivarian Republic of)  ...   0.0   0.0   0.0   0.0   0.0
        Viet Nam                            ...   0.0   0.0   0.0   0.0   0.0
        Virgin Islands (British)            ...   0.0   0.0   0.0   0.0   0.0
        Yemen                               ...   0.0   0.0   0.0   0.0   0.0

                                            2016  2017  2018  2019  2020
Country Partner_country
Austria Albania                              0.0   0.0   0.0   0.0   0.0
        Algeria                              0.0   0.0   0.0   0.0   0.0
        Andorra                              0.0   0.0   0.0   0.0   0.0
        Angola                               0.0   0.0   0.0   0.0   0.0
        Argentina                            0.0   0.0   0.0   0.0   0.0
...                                          ...   ...   ...   ...   ...
Sweden  Uzbekistan                           0.0   0.0   0.0   0.0   0.0
        Venezuela (Bolivarian Republic of)   0.0   0.0   0.0   0.0   0.0
        Viet Nam                             0.0   0.0   0.0   0.0   0.0
        Virgin Islands (British)             0.0   0.0   0.0   0.0   0.0
        Yemen                                0.0   0.0   0.0   0.0   0.0

[4131 rows x 36 columns]

In [31]:
# create new column 'Partner_EU?' and fill with True/False based on whether Partner_country is in EU dictionary
EU_imports_grouped['Partner_EU'] = EU_imports_grouped['partner'].isin(EU_countries['Alpha_2_code'])
EU_imports_grouped

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Partner_EU
0,AT,Austria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
1,BE,Belgium,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
2,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
3,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4451,RO,Romania,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4452,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4453,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4454,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False

In [32]:
EU_imports_grouped.columns

Index(['Alpha_2_code', 'Country', 'EU?', 'partner', 'Partner_country', 'siec',
       'unit', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', 'Partner_EU'],
      dtype='object')

In [33]:
EU_imports_grouped = EU_imports_grouped[['Alpha_2_code', 'Country', 'EU?', 'partner', 'Partner_country', 'Partner_EU',
                                         'siec', 'unit', '1990', '1991', '1992', '1993',
                                         '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
                                         '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                                         '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
                                         '2018', '2019', '2020']]
EU_imports_grouped

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AT,Austria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
EU_imports_grouped.columns.get_loc('1990')

8

In [35]:
EU_imports_grouped.columns.get_loc('2020')

38

In [36]:
EU_imports_grouped.iloc[:,8:39].sum(axis=1)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
4450    0.0
4451    0.0
4452    0.0
4453    0.0
4454    0.0
Length: 4455, dtype: float64

In [37]:
EU_imports_grouped['TOTAL'] = EU_imports_grouped.iloc[:,8:39].sum(axis=1)
EU_imports_grouped

/var/folders/w_/gltqg5356fv2085dww7dq0x40000gn/T/ipykernel_69465/443307255.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EU_imports_grouped['TOTAL'] = EU_imports_grouped.iloc[:,8:39].sum(axis=1)

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
0,AT,Austria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
EU_imports_grouped['TOTAL'].unique()

array([0.00000000e+00, 3.10000000e-02, 2.10000000e-02, 8.03900000e+06,
       2.08522100e+06, 1.84230000e+08, 1.60000000e+04, 4.71310000e+07,
       4.65410520e+07, 7.52000000e+05, 1.00000000e+03, 6.90432150e+07,
       5.50285000e+07, 1.00000000e+04, 7.63000000e+05, 7.07943860e+07,
       3.54028080e+07, 9.38091290e+07, 7.07850000e+07, 1.87409730e+07,
       6.89612000e+07, 9.00000000e+03, 8.21900000e+06, 1.31440660e+07,
       1.15655000e+08, 7.88273460e+07, 6.87449510e+08, 1.57200000e+06,
       1.07021200e+06, 2.24000000e+06, 2.02346037e+08, 2.01195000e+08,
       6.90135900e+06, 5.00000000e+04, 1.10000000e+04, 1.78018000e+08,
       3.10173075e+08, 3.27900000e+05, 5.87093110e+07, 7.67487870e+07,
       3.15275710e+07, 1.53673638e+08, 4.06634933e+08, 1.44189550e+08,
       8.00000000e+03, 2.01620000e+07, 1.67000000e+05, 1.24251000e+08,
       2.70238900e+06, 8.46280000e+07, 1.31100000e+07, 4.95340930e+07,
       6.49789000e+05, 1.82403240e+07, 4.64000000e+05, 5.94806560e+07,
       8.70000000e+04, 1.82764621e+08, 3.30600000e+07, 1.48900000e+06,
       4.83060000e+07, 2.07898800e+08, 4.33599000e+08, 2.00320864e+08,
       4.78833412e+08, 8.33272817e+06, 5.40170000e+07, 2.44000000e+06,
       8.17139220e+07, 1.93568230e+07, 3.25000000e+05, 5.80742000e+07,
       1.89988280e+07, 1.50600000e+06, 3.65607068e+05, 1.83300000e+07,
       1.95728600e+07, 5.18561300e+06, 2.39585700e+06, 2.63182820e+07,
       8.63741300e+06, 8.30000000e+05, 2.44210000e+07, 9.47800000e+06,
       1.22240000e+07, 8.85071000e+07, 2.15347000e+06, 5.15900000e+06,
       1.67306900e+06, 3.09468395e+05, 3.61230000e+07, 2.40000000e+05,
       3.00000000e+04, 6.77670000e+04, 1.76012200e+08, 4.45000000e+07,
       1.68427800e+06, 1.03500451e+08, 3.75800000e+06, 5.19548880e+07,
       2.24262000e+08, 7.20000000e-02, 1.80900000e+07, 1.45120000e+07,
       9.42550000e+07, 3.95100000e+06, 5.28840000e+07, 1.54460000e+07,
       2.21790000e+07, 2.42400000e+07, 2.87200000e+06, 1.93110000e+07,
       2.18272532e+08, 2.49900000e+07, 2.48130000e+06, 1.12620000e+07,
       6.58300000e+07, 1.15424839e+08, 4.95121220e+07, 1.32580000e+07,
       3.13932500e+06, 9.72800000e+06, 1.60864000e+07, 7.14900000e+06,
       1.24713150e+07, 7.00000000e+04, 1.81300000e+06, 2.14991000e+08,
       3.36098000e+07, 2.44663450e+07, 2.63000000e+05, 2.61210000e+07,
       1.23488278e+08, 2.19862000e+08, 1.66376000e+07, 1.25200000e+06,
       3.86434880e+07, 8.50561600e+06, 6.76370000e+07, 1.31125831e+08,
       1.19266090e+07, 1.90877000e+08, 5.06342000e+05, 4.66000000e+05,
       5.53891364e+08, 4.09274600e+08, 7.23578320e+07, 3.05505673e+08,
       1.25827400e+09, 3.05421794e+08, 5.10480000e+07, 1.65289000e+08,
       3.17899204e+08, 4.51721000e+08, 2.87022122e+08, 2.49710100e+08,
       3.71704000e+08, 2.80931180e+07, 1.36393096e+09, 2.10197000e+08,
       1.97409339e+08, 1.15773720e+08, 6.21732078e+08, 2.49563250e+08,
       8.75796290e+07, 3.89450000e+08, 1.59305994e+08, 2.74098000e+08,
       6.56733000e+05, 2.19430000e+07, 1.10849000e+08, 2.02870980e+07,
       5.39330100e+06, 9.43300000e+06, 6.14700000e+05, 2.68192820e+07,
       7.46173900e+06, 4.00000000e+03])

In [39]:
EU_imports_grouped.dtypes

Alpha_2_code        object
Country             object
EU?                   bool
partner             object
Partner_country     object
Partner_EU            bool
siec                object
unit                object
1990               float64
1991               float64
1992               float64
1993               float64
1994               float64
1995               float64
1996               float64
1997               float64
1998               float64
1999               float64
2000               float64
2001               float64
2002               float64
2003               float64
2004               float64
2005               float64
2006               float64
2007               float64
2008               float64
2009               float64
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
TOTAL              float64
dtype: object

In [40]:
EU_imports_filtered = EU_imports_filtered[EU_imports_filtered['unit'] == 'GWH']
EU_imports_filtered

,Alpha_2_code,Country,EU?,partner,Partner_country,siec,unit,1990,1991,1992,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Partner_EU
0,AT,Austria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
1,BE,Belgium,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
2,BG,Bulgaria,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
3,CY,Cyprus,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4,CZ,Czechia,True,AD,Andorra,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4451,RO,Romania,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4452,SE,Sweden,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4453,SI,Slovenia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
4454,SK,Slovakia,True,ZA,South Africa,E7000,GWH,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False

In [41]:
EU_imports_grouped['Partner_EU'].unique()

array([False,  True])

In [42]:
EU_imports_grouped_DE = EU_imports_grouped.query("Country == 'Germany'")
EU_imports_grouped_DE

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
5,DE,Germany,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,DE,Germany,True,AE,United Arab Emirates (the),False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,DE,Germany,True,AFR_OTH,NaN,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,DE,Germany,True,AL,Albania,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113,DE,Germany,True,AM,Armenia,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4325,DE,Germany,True,VG,Virgin Islands (British),False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4352,DE,Germany,True,VN,Viet Nam,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4379,DE,Germany,True,XK,NaN,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4406,DE,Germany,True,YE,Yemen,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4433,DE,Germany,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
EU_imports_grouped_DE = EU_imports_grouped_DE.query("Partner_country == 'Denmark'")
EU_imports_grouped_DE

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
1193,DE,Germany,True,DK,Denmark,True,E7000,GWH,4721000.0,4029000.0,...,8834000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124251000.0

In [44]:
# remove NaN in Partner_country
EU_imports_grouped

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
0,AT,Austria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
EU_imports_cleaned = EU_imports_grouped.dropna()
EU_imports_cleaned

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
0,AT,Austria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,BE,Belgium,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,BG,Bulgaria,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,CY,Cyprus,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,CZ,Czechia,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4450,PT,Portugal,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4451,RO,Romania,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4452,SE,Sweden,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4453,SI,Slovenia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4454,SK,Slovakia,True,ZA,South Africa,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [46]:
EU_imports_cleaned = EU_imports_cleaned[EU_imports_cleaned['TOTAL']!=0]
EU_imports_cleaned

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
9,ES,Spain,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.015,0.016,3.100000e-02
11,FR,France,True,AD,Andorra,False,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.021,2.100000e-02
89,EL,Greece,True,AL,Albania,False,E7000,GWH,165000.0,416000.0,...,17000.0,1380000.0,105000.0,332000.0,822000.0,80000.0,1062000.0,475000.000,622000.000,8.039000e+06
274,CZ,Czechia,True,AT,Austria,True,E7000,GWH,34000.0,221000.0,...,0.0,0.0,265000.0,41000.0,136000.0,62478.0,112561.0,144762.000,378420.000,2.085221e+06
275,DE,Germany,True,AT,Austria,True,E7000,GWH,4092000.0,4367000.0,...,8221000.0,8842000.0,7144000.0,7071000.0,5979000.0,4008000.0,4793000.0,4876000.000,6101000.000,1.842300e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4031,EL,Greece,True,TR,Turkey,False,E7000,GWH,0.0,0.0,...,1703000.0,52000.0,1907000.0,2814000.0,1444000.0,3198000.0,2907000.0,2664000.000,1839000.000,2.194300e+07
4144,HU,Hungary,True,UA,Ukraine,False,E7000,GWH,12160000.0,6605000.0,...,4014000.0,4836000.0,5614000.0,5550000.0,4412000.0,4563000.0,5054000.0,4014000.000,2484000.000,1.108490e+08
4152,PL,Poland,True,UA,Ukraine,False,E7000,GWH,0.0,0.0,...,1005000.0,1029000.0,686000.0,66000.0,957000.0,895000.0,1410155.0,1376820.000,1484123.000,2.028710e+07
4154,RO,Romania,True,UA,Ukraine,False,E7000,GWH,0.0,0.0,...,524000.0,64000.0,122000.0,172000.0,29000.0,473077.0,73315.0,501061.000,583848.000,5.393301e+06
4157,SK,Slovakia,True,UA,Ukraine,False,E7000,GWH,0.0,0.0,...,56000.0,173000.0,62000.0,64000.0,64000.0,9000.0,170000.0,30000.000,93000.000,9.433000e+06

In [47]:
# add grand total

EU_imports_cleaned[['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL']].sum()

1990     1.614900e+08
1991     1.423710e+08
1992     1.519390e+08
1993     1.714520e+08
1994     1.639930e+08
1995     1.768410e+08
1996     1.886970e+08
1997     1.929880e+08
1998     1.839610e+08
1999     2.111060e+08
2000     2.465144e+08
2001     2.469651e+08
2002     2.739346e+08
2003     2.828752e+08
2004     2.724533e+08
2005     3.154110e+08
2006     3.008214e+08
2007     3.121456e+08
2008     3.017732e+08
2009     2.864865e+08
2010     2.853822e+08
2011     3.161901e+08
2012     3.461738e+08
2013     3.182331e+08
2014     3.489609e+08
2015     3.743201e+08
2016     3.525597e+08
2017     3.531522e+08
2018     3.598576e+08
2019     3.548831e+08
2020     3.595373e+08
TOTAL    8.353468e+09
dtype: float64

In [86]:
EU_imports_cleaned['EU?'].unique()

array([ True])

In [83]:
EU_pivot = pd.pivot_table(EU_imports_cleaned, index=['Country', 'EU?'],
                         values=['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL'],
                          fill_value='')
EU_pivot

,,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
Country,EU?,,,,,,,,,,,,,,,,,,,,,
Austria,True,1.139833e+06,1.417167e+06,1.529167e+06,1.345333e+06,1.369833e+06,1.214500e+06,1.571333e+06,1.501333e+06,1.717333e+06,1.934667e+06,...,3.904952e+06,4.159928e+06,4.451954e+06,4.898194e+06,4.394360e+06,4.893738e+06,4.679344e+06,4.341141e+06,4.087082e+06,9.231520e+07
Belgium,True,1.196250e+06,1.249500e+06,1.462250e+06,1.897500e+06,2.263250e+06,2.349500e+06,2.409250e+06,2.493750e+06,1.957000e+06,2.264750e+06,...,4.212000e+06,4.310750e+06,5.447750e+06,5.928500e+06,3.662000e+06,3.547350e+06,5.408575e+06,3.152000e+06,3.308800e+06,1.021650e+08
Bulgaria,True,0.000000e+00,0.000000e+00,6.580000e+04,3.200000e+03,0.000000e+00,2.040000e+04,0.000000e+00,1.148000e+05,1.128000e+05,3.340000e+05,...,4.706000e+05,6.702000e+05,8.638000e+05,8.502000e+05,9.136000e+05,7.410846e+05,4.444663e+05,6.089894e+05,7.413472e+05,1.085349e+07
Croatia,True,0.000000e+00,0.000000e+00,0.000000e+00,5.977500e+05,6.137500e+05,6.370000e+05,8.067500e+05,8.387500e+05,0.000000e+00,3.047500e+05,...,3.293500e+06,2.815000e+06,2.724500e+06,3.289500e+06,3.099500e+06,3.039475e+06,3.173350e+06,2.850200e+06,2.622750e+06,4.920652e+07
Czechia,True,2.044750e+06,1.798500e+06,1.539000e+06,1.488000e+06,1.353750e+06,1.680500e+06,2.202750e+06,2.253250e+06,2.095750e+06,2.245750e+06,...,2.635750e+06,2.153000e+06,2.960500e+06,4.036500e+06,3.454250e+06,3.768000e+06,2.893352e+06,2.756553e+06,3.342013e+06,7.274842e+07
Denmark,True,2.993250e+06,7.687500e+05,2.161750e+06,1.569750e+06,4.452500e+05,1.003250e+06,9.452500e+05,9.490000e+05,8.200000e+05,1.240750e+06,...,3.980000e+06,2.864750e+06,3.175500e+06,3.911187e+06,3.744114e+06,3.804527e+06,3.908402e+06,3.995475e+06,4.648493e+06,7.635545e+07
Estonia,True,0.000000e+00,0.000000e+00,0.000000e+00,7.366667e+04,1.050000e+05,8.166667e+04,8.000000e+04,7.000000e+04,4.600000e+04,4.600000e+04,...,9.033333e+05,9.040000e+05,1.243333e+06,1.817333e+06,1.192333e+06,7.603333e+05,1.017667e+06,1.620333e+06,2.455667e+06,1.569900e+07
Finland,True,2.751750e+06,1.982750e+06,2.266750e+06,2.003250e+06,1.792750e+06,2.125250e+06,1.341750e+06,2.025750e+06,2.395500e+06,2.839000e+06,...,4.772250e+06,4.397750e+06,5.405500e+06,5.364750e+06,5.527500e+06,5.551000e+06,5.637000e+06,5.984500e+06,5.411750e+06,1.129302e+08
France,True,1.104833e+06,9.193333e+05,7.895000e+05,6.105000e+05,6.196667e+05,4.723333e+05,6.023333e+05,7.063333e+05,7.596667e+05,8.275000e+05,...,1.837167e+06,1.856833e+06,1.309833e+06,1.631167e+06,3.100000e+06,3.154697e+06,2.187560e+06,2.487162e+06,2.984384e+06,4.336714e+07
Germany,True,2.791889e+06,3.379556e+06,3.157556e+06,3.736444e+06,3.989778e+06,4.415000e+06,4.156000e+06,4.223556e+06,4.257222e+06,4.510889e+06,...,5.140889e+06,3.407222e+06,3.176333e+06,2.847000e+06,2.298556e+06,1.993111e+06,2.381667e+06,3.219556e+06,3.436333e+06,1.293354e+08
Greece,True,1.662500e+05,1.872500e+05,1.208750e+05,1.366250e+05,1.020000e+05,1.737500e+05,3.330000e+05,3.753750e+05,3.125000e+05,2.263750e+05,...,7.442500e+05,7.235000e+05,1.182625e+06,1.385125e+06,1.229125e+06,1.087000e+06,1.068750e+06,1.383375e+06,1.228875e+06,2.066112e+07
Hungary,True,2.216500e+06,1.401667e+06,8.313333e+05,6.821667e+05,4.923333e+05,5.350000e+05,5.788333e+05,7.350000e+05,5.590000e+05,7.248333e+05,...,2.828333e+06,2.772500e+06,3.179833e+06,3.322500e+06,2.991833e+06,3.300500e+06,3.102167e+06,3.308833e+06,3.196000e+06,6.195067e+07
Italy,True,5.082429e+06,5.064857e+06,5.135286e+06,5.729857e+06,5.527857e+06,5.523143e+06,5.449857e+06,5.689571e+06,5.947571e+06,6.076857e+06,...,6.486714e+06,6.334000e+06,6.678143e+06,7.264143e+06,6.168714e+06,6.127840e+06,6.738601e+06,6.282134e+06,5.684277e+06,1.948473e+08
Latvia,True,0.000000e+00,0.000000e+00,0.000000e+00,6.680000e+05,6.620000e+05,6.617500e+05,8.595000e+05,4.560000e+05,2.285000e+05,6.492500e+05,...,1.233750e+06,1.251250e+06,1.335000e+06,1.311500e+06,1.207000e+06,1.018228e+06,1.293420e+06,1.152690e+06,1.043341e+06,2.508193e+07
Lithuania,True,9.076000e+05,7.450000e+05,1.067600e+06,1.147200e+06,1.422800e+06,1.054000e+06,8.364000e+05,9.048000e+05,9.144000e+05,9.786000e+05,...,1.612000e+06,1.614600e+06,1.704200e+06,1.587600e+06,2.221200e+06,2.385240e+06,2.569500e+06,2.653580e+06,2.402680e+06,4.203940e+07
Luxembourg,True,1.559333e+06,1.617667e+06,1.503667e+06,1.481667e+06,1.673000e+06,1.915333e+06,1.904000e+06,2.010667e+06,2.112667e+06,2.070667e+06,...,2.244033e+06,2.283841e+06,2.320392e+06,2.506252e+06,2.572798e+06,2.522230e+06,2.517671e+06,2.272507e+06,2.181164e+06,6.580306e+07
Malta,True,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.054000e+06,1.526688e+06,8.970660e+05,6.312930e+05,6.567560e+05,4.198100e+05,5.185613e+06
Netherlands (the),True,9.679000e+05,9.778000e+05,8.906000e+05,1.057200e+06,1.085000e+06,1.197900e+06,1.128800e+06,1.310700e+06,1.223400e+06,2.117600e+06,...,3.189300e+06,3.311000e+06,3.284400e+06,3.075247e+06,2.411799e+06,2.226696e+06,2.656620e+06,2.001832e+06,1.923240e+06,6.142703e+07
Poland,True,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+05,6.518571e+05,6.222857e+05,6.858571e+05,7.652857e+05,6.582857e+05,4.987143e+05,...,1.400429e+06,1.114429e+06,1.929714e+06,2.065571e+06,2.002429e+06,1.895857e+06,1.973686e+06,2.552618e+06,2.946303e+06,3.248346e+07
Portugal,True,1.733000e+06,1.712000e+06,2.538000e+06,2.077000e+06,2.257000e+06,2.655000e+06,4.116000e+06,5.376000e+06,3.974000e+06,3.628000e+06,...,1.076600e+07,8.100000e+06,7.247000e+06,8.077000e+06,4.616000e+06,5.505732e+06,5.667568e+06,8.099208e+06,7.553113e+06,1.827646e+08
Romania,True,0.000000e+00,0.000000e+00,2.027857e+05,1.173571e+05,0.000000e+00,0.000000e+00,0.000000e+00,5.550000e+04,5.171429e+04,7.878571e+04,...,2.787857e+05,1.955000e+05,2.007857e+05,3.208571e+05,2.983571e+05,3.458396e+05,2.640424e+05,3.923309e+05,5.894034e+05,4.523974e+06
Slovakia,True,0.000000e+00,0.000000e+00,0.000000e+00,1.074250e+06,7.017500e+05,8.620000e+05,1.468750e+06,1.699500e+06,1.095250e+06,9.345000e+05,...,3.368000e+06,2.679750e+06,3.241000e+06,3.749750e+06,3.312250e+06,3.890750e+06,3.107000e+06,3.384500e+06,3.322250e+06,6.369675e+07
Slovenia,True,0.000000e+00,0.000000e+00,3.655556e+04,7.844444e+04,4.977778e+04,8.222222e+04,9.500000e+04,9.111111e+04,7.900000e+04,6.622222e+04,...,8.280000e+05,8.356667e+05,8.060000e+05,1.005000e+06,9.287778e+05,1.014726e+06,9.922488e+05,1.002364e+06,7.911056e+05,1.738155e+07
Spain,True,8.020000e+05,7.707500e+05,1.087750e+06,1.151500e+06,1.276500e+06,1.908250e+06,1.687500e+06,1.149250e+06,2.241000e+06,2.989750e+06,...,1.946750e+06,2.471750e+06,3.077500e+06,3.739000e+06,5.461250e+06,5.940500e+06,6.004500e+06,4.680206e+06,4.482087e+06,7.947479e+07
Sweden,True,2.151500e+06,1.037500e+06,1.474500e+06,1.329667e+06,1.113500e+06,1.286667e+06,2.647500e+06,1.708667e+06,1.017000e+06,1.409333e+06,...,1.947000e+06,2.112333e+06,2.308667e+06,1.549000e+06,2.381167e+06,1.982667e+06,2.033667e+06,1.511667e+06,1.971167e+06,6.490833e+07

In [48]:
EU_Totals = EU_imports_cleaned.append(EU_imports_cleaned[['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL']].sum().rename('GRAND TOTAL')).fillna('')
EU_Totals

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
9,ES,Spain,1.0,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.500000e-02,1.600000e-02,3.100000e-02
11,FR,France,1.0,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2.100000e-02,2.100000e-02
89,EL,Greece,1.0,AL,Albania,0.0,E7000,GWH,165000.0,416000.0,...,17000.0,1380000.0,105000.0,332000.0,822000.0,80000.0,1.062000e+06,4.750000e+05,6.220000e+05,8.039000e+06
274,CZ,Czechia,1.0,AT,Austria,1.0,E7000,GWH,34000.0,221000.0,...,0.0,0.0,265000.0,41000.0,136000.0,62478.0,1.125610e+05,1.447620e+05,3.784200e+05,2.085221e+06
275,DE,Germany,1.0,AT,Austria,1.0,E7000,GWH,4092000.0,4367000.0,...,8221000.0,8842000.0,7144000.0,7071000.0,5979000.0,4008000.0,4.793000e+06,4.876000e+06,6.101000e+06,1.842300e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4144,HU,Hungary,1.0,UA,Ukraine,0.0,E7000,GWH,12160000.0,6605000.0,...,4014000.0,4836000.0,5614000.0,5550000.0,4412000.0,4563000.0,5.054000e+06,4.014000e+06,2.484000e+06,1.108490e+08
4152,PL,Poland,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,1005000.0,1029000.0,686000.0,66000.0,957000.0,895000.0,1.410155e+06,1.376820e+06,1.484123e+06,2.028710e+07
4154,RO,Romania,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,524000.0,64000.0,122000.0,172000.0,29000.0,473077.0,7.331500e+04,5.010610e+05,5.838480e+05,5.393301e+06
4157,SK,Slovakia,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,56000.0,173000.0,62000.0,64000.0,64000.0,9000.0,1.700000e+05,3.000000e+04,9.300000e+04,9.433000e+06
GRAND TOTAL,,,,,,,,,161490000.0,142371000.0,...,346173813.0,318233094.0,348960899.0,374320132.0,352559687.0,353152162.0,3.598576e+08,3.548831e+08,3.595373e+08,8.353468e+09

In [49]:
pivot = pd.pivot_table(data=EU_Totals, index=['Country', 'Partner_EU', 'Partner_country'],
                      values=['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL'],
                      aggfunc=['sum'])
pivot

                                            sum                            \
                                           1990         1991         1992
Country Partner_EU Partner_country
                                    161490000.0  142371000.0  151939000.0
Austria 0.0        Switzerland          76000.0     494000.0     394000.0
        1.0        Czechia            2975000.0    2910000.0    3299000.0
                   Germany            3559000.0    4548000.0    4960000.0
                   Hungary             212000.0     348000.0     483000.0
...                                         ...          ...          ...
Sweden  1.0        Denmark             219000.0     815000.0    1474000.0
                   Finland             360000.0     662000.0     691000.0
                   Germany                  0.0          0.0          0.0
                   Lithuania                0.0          0.0          0.0
                   Poland                   0.0          0.0          0.0

                                                                           \
                                           1993         1994         1995
Country Partner_EU Partner_country
                                    171452000.0  163993000.0  176841000.0
Austria 0.0        Switzerland         610000.0     973000.0     290000.0
        1.0        Czechia            2765000.0    2755000.0    2081000.0
                   Germany            4196000.0    4004000.0    4580000.0
                   Hungary             461000.0     404000.0     270000.0
...                                         ...          ...          ...
Sweden  1.0        Denmark            1312000.0    1931000.0     627000.0
                   Finland             379000.0     298000.0     213000.0
                   Germany                  0.0      14000.0      20000.0
                   Lithuania                0.0          0.0          0.0
                   Poland                   0.0          0.0          0.0

                                                                           \
                                           1996         1997         1998
Country Partner_EU Partner_country
                                    188697000.0  192988000.0  183961000.0
Austria 0.0        Switzerland         371000.0     420000.0     204000.0
        1.0        Czechia            2227000.0    2608000.0    2777000.0
                   Germany            5985000.0    5176000.0    6000000.0
                   Hungary             694000.0     757000.0    1276000.0
...                                         ...          ...          ...
Sweden  1.0        Denmark            8668000.0    5243000.0    2155000.0
                   Finland            2151000.0     932000.0     852000.0
                   Germany            1011000.0     400000.0      88000.0
                   Lithuania                0.0          0.0          0.0
                   Poland                   0.0          0.0          0.0

                                                 ...               \
                                           1999  ...         2012
Country Partner_EU Partner_country               ...
                                    211106000.0  ...  346173813.0
Austria 0.0        Switzerland         376000.0  ...     127149.0
        1.0        Czechia            3635000.0  ...   10308122.0
                   Germany            5573000.0  ...   12525856.0
                   Hungary            2018000.0  ...     334605.0
...                                         ...  ...          ...
Sweden  1.0        Denmark            1611000.0  ...    1316000.0
                   Finland             847000.0  ...      23000.0
                   Germany              92000.0  ...     259000.0
                   Lithuania                0.0  ...          0.0
                   Poland                   0.0  ...     129000.0

                                                                           \
                                           2013         2014         2015
Country Partner_EU Partner_country
                                    318233094.0  348960899.0  374320132.0
Austria 0.0        Switzerland         254164.0     547904.0     269870.0
        1.0        Czechia           10508306.0   11952611.0   12340895.0
                   Germany           12382059.0   13142500.0   16155647.0
                   Hungary            1013631.0     547007.0     525491.0
...                                         ...          ...          ...
Sweden  1.0        Denmark            3806000.0    3153000.0    1907000.0
                   Finland             204000.0          0.0       2000.0
                   Germany             998000.0     736000.0     143000.0
                   Lithuania                0.0          0.0          0.0
                   Poland              762000.0     107000.0      20000.0

                                                                            \
                                           2016         2017          2018
Country Partner_EU Partner_country
                                    352559687.0  353152162.0  3.598576e+08
Austria 0.0        Switzerland         391281.0     463061.0  1.200032e+06
        1.0        Czechia           10255121.0   11005785.0  1.086400e+07
                   Germany           14854492.0   17509117.0  1.499800e+07
                   Hungary             431724.0     134420.0  5.910000e+05
...                                         ...          ...           ...
Sweden  1.0        Denmark            4015000.0    2203000.0  2.795000e+06
                   Finland              60000.0      88000.0  1.790000e+05
                   Germany             798000.0     251000.0  4.520000e+05
                   Lithuania           121000.0     113000.0  2.180000e+05
                   Poland              175000.0     150000.0  3.750000e+05


                                            2019          2020         TOTAL
Country Partner_EU Partner_country
                                    3.548831e+08  3.595373e+08  8.353468e+09
Austria 0.0        Switzerland      1.610522e+06  1.734078e+06  1.314407e+07
        1.0        Czechia          9.431534e+06  8.687133e+06  2.023460e+08
                   Germany          1.479672e+07  1.377828e+07  3.101731e+08
                   Hungary          3.886900e+04  1.018160e+05  1.935682e+07
...                                          ...           ...           ...
Sweden  1.0        Denmark          2.805000e+06  1.648000e+06  8.462800e+07
                   Finland          5.000000e+04  1.000000e+03  4.830600e+07
                   Germany          5.640000e+05  3.860000e+05  2.016200e+07
                   Lithuania        2.830000e+05  9.500000e+04  8.300000e+05
                   Poland           1.880000e+05  1.200000e+04  1.126200e+07

[139 rows x 32 columns]

In [50]:
pivot_groups = pd.pivot_table(data=EU_Totals, index=['Country', 'Partner_EU'],
                      values=['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL'],
                      aggfunc=['sum'])
pivot_groups

                                      sum                            \
                                     1990         1991         1992
Country           Partner_EU
                              161490000.0  142371000.0  151939000.0
Austria           0.0             76000.0     494000.0     394000.0
                  1.0           6763000.0    8009000.0    8781000.0
Belgium           1.0           4785000.0    4998000.0    5849000.0
Bulgaria          0.0                 0.0          0.0     198000.0
                  1.0                 0.0          0.0     131000.0
Croatia           0.0                 0.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Czechia           1.0           8179000.0    7194000.0    6156000.0
Denmark           0.0           3958000.0    1198000.0    3159000.0
                  1.0           8015000.0    1877000.0    5488000.0
Estonia           0.0                 0.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Finland           0.0           4656000.0    5184000.0    4590000.0
                  1.0           6351000.0    2747000.0    4477000.0
France            0.0            495000.0     637000.0     628000.0
                  1.0           6134000.0    4879000.0    4109000.0
Germany           0.0           5698000.0    6436000.0    4844000.0
                  1.0          19429000.0   23980000.0   23574000.0
Greece            0.0            994000.0    1498000.0     897000.0
                  1.0            336000.0          0.0      70000.0
Hungary           0.0          12222000.0    6762000.0    3245000.0
                  1.0           1077000.0    1648000.0    1743000.0
Italy             0.0          17085000.0   15833000.0   18007000.0
                  1.0          18492000.0   19621000.0   17940000.0
Latvia            0.0                 0.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Lithuania         0.0           1414000.0    1364000.0    2084000.0
                  1.0           3124000.0    2361000.0    3254000.0
Luxembourg        1.0           4678000.0    4853000.0    4511000.0
Malta             1.0                 0.0          0.0          0.0
Netherlands (the) 0.0                 0.0       1000.0       5000.0
                  1.0           9679000.0    9777000.0    8901000.0
Poland            0.0                 0.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Portugal          1.0           1733000.0    1712000.0    2538000.0
Romania           0.0                 0.0          0.0    2706000.0
                  1.0                 0.0          0.0     133000.0
Slovakia          0.0                 0.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Slovenia          0.0                 0.0          0.0     237000.0
                  1.0                 0.0          0.0      92000.0
Spain             0.0                 0.0          0.0          0.0
                  1.0           3208000.0    3083000.0    4351000.0
Sweden            0.0          12330000.0    4748000.0    6682000.0
                  1.0            579000.0    1477000.0    2165000.0

                                                                     \
                                     1993         1994         1995
Country           Partner_EU
                              171452000.0  163993000.0  176841000.0
Austria           0.0            610000.0     973000.0     290000.0
                  1.0           7462000.0    7246000.0    6997000.0
Belgium           1.0           7590000.0    9053000.0    9398000.0
Bulgaria          0.0             16000.0          0.0     102000.0
                  1.0                 0.0          0.0          0.0
Croatia           0.0            502000.0     253000.0     264000.0
                  1.0           1889000.0    2202000.0    2284000.0
Czechia           1.0           5952000.0    5415000.0    6722000.0
Denmark           0.0           2140000.0     933000.0    1676000.0
                  1.0           4139000.0     848000.0    2337000.0
Estonia           0.0            221000.0     315000.0     245000.0
                  1.0                 0.0          0.0          0.0
Finland           0.0           4825000.0    5383000.0    4796000.0
                  1.0           3188000.0    1788000.0    3705000.0
France            0.0            484000.0     761000.0     557000.0
                  1.0           3179000.0    2957000.0    2277000.0
Germany           0.0           5816000.0    6692000.0    6244000.0
                  1.0          27812000.0   29216000.0   33491000.0
Greece            0.0            409000.0     492000.0     694000.0
                  1.0            684000.0     324000.0     696000.0
Hungary           0.0           1811000.0    1037000.0    1592000.0
                  1.0           2282000.0    1917000.0    1618000.0
Italy             0.0          19535000.0   19088000.0   18940000.0
                  1.0          20574000.0   19607000.0   19722000.0
Latvia            0.0            373000.0    1039000.0    1245000.0
                  1.0           2299000.0    1609000.0    1402000.0
Lithuania         0.0           2456000.0    3332000.0    2416000.0
                  1.0           3280000.0    3782000.0    2854000.0
Luxembourg        1.0           4445000.0    5019000.0    5746000.0
Malta             1.0                 0.0          0.0          0.0
Netherlands (the) 0.0                 0.0      13000.0     137000.0
                  1.0          10572000.0   10837000.0   11842000.0
Poland            0.0           1052000.0          0.0     336000.0
                  1.0           4548000.0    4563000.0    4020000.0
Portugal          1.0           2077000.0    2257000.0    2655000.0
Romania           0.0           1643000.0          0.0          0.0
                  1.0                 0.0          0.0          0.0
Slovakia          0.0            341000.0     853000.0    1574000.0
                  1.0           3956000.0    1954000.0    1874000.0
Slovenia          0.0            621000.0     239000.0     328000.0
                  1.0             85000.0     209000.0     412000.0
Spain             0.0                 0.0          0.0          0.0
                  1.0           4606000.0    5106000.0    7633000.0
Sweden            0.0           6287000.0    4438000.0    6860000.0
                  1.0           1691000.0    2243000.0     860000.0

                                                                     \
                                     1996         1997         1998
Country           Partner_EU
                              188697000.0  192988000.0  183961000.0
Austria           0.0            371000.0     420000.0     204000.0
                  1.0           9057000.0    8588000.0   10100000.0
Belgium           1.0           9637000.0    9975000.0    7828000.0
Bulgaria          0.0                 0.0     137000.0     190000.0
                  1.0                 0.0     437000.0     374000.0
Croatia           0.0           1039000.0     926000.0          0.0
                  1.0           2188000.0    2429000.0          0.0
Czechia           1.0           8811000.0    9013000.0    8383000.0
Denmark           0.0           1755000.0    1680000.0    1589000.0
                  1.0           2026000.0    2116000.0    1691000.0
Estonia           0.0            240000.0     210000.0     138000.0
                  1.0                 0.0          0.0          0.0
Finland           0.0           4647000.0    4360000.0    4890000.0
                  1.0            720000.0    3743000.0    4692000.0
France            0.0            326000.0     641000.0    1234000.0
                  1.0           3288000.0    3597000.0    3324000.0
Germany           0.0           5398000.0    5664000.0    5792000.0
                  1.0          32006000.0   32348000.0   32523000.0
Greece            0.0           1736000.0    1552000.0    1414000.0
                  1.0            928000.0    1451000.0    1086000.0
Hungary           0.0           1448000.0    1377000.0    1101000.0
                  1.0           2025000.0    3033000.0    2253000.0
Italy             0.0          17479000.0   19958000.0   21479000.0
                  1.0          20670000.0   19869000.0   20154000.0
Latvia            0.0           1438000.0     820000.0     650000.0
                  1.0           2000000.0    1004000.0     264000.0
Lithuania         0.0           1999000.0    1670000.0     993000.0
                  1.0           2183000.0    2854000.0    3579000.0
Luxembourg        1.0           5712000.0    6032000.0    6338000.0
Malta             1.0                 0.0          0.0          0.0
Netherlands (the) 0.0                 0.0      23000.0      65000.0
                  1.0          11288000.0   13084000.0   12169000.0
Poland            0.0            681000.0    1151000.0    1484000.0
                  1.0           4120000.0    4206000.0    3124000.0
Portugal          1.0           4116000.0    5376000.0    3974000.0
Romania           0.0                 0.0     603000.0     638000.0
                  1.0                 0.0     174000.0      86000.0
Slovakia          0.0           2203000.0    2315000.0          0.0
                  1.0           3672000.0    4483000.0    4381000.0
Slovenia          0.0            284000.0     456000.0     500000.0
                  1.0            571000.0     364000.0     211000.0
Spain             0.0                 0.0       2000.0          0.0
                  1.0           6750000.0    4595000.0    8964000.0
Sweden            0.0           4055000.0    3677000.0    3007000.0
                  1.0          11830000.0    6575000.0    3095000.0

                                           ...                            \
                                     1999  ...         2012         2013
Country           Partner_EU               ...
                              211106000.0  ...  346173813.0  318233094.0
Austria           0.0            376000.0  ...     127149.0     254164.0
                  1.0          11232000.0  ...   23302566.0   24705406.0
Belgium           1.0           9059000.0  ...   16848000.0   17243000.0
Bulgaria          0.0            667000.0  ...      16000.0     436000.0
                  1.0           1003000.0  ...    2337000.0    2915000.0
Croatia           0.0            361000.0  ...    2462000.0    5762000.0
                  1.0            858000.0  ...   10712000.0    5498000.0
Czechia           1.0           8983000.0  ...   10543000.0    8612000.0
Denmark           0.0           2793000.0  ...    5455000.0    2553000.0
                  1.0           2170000.0  ...   10465000.0    8906000.0
Estonia           0.0            138000.0  ...          0.0          0.0
                  1.0                 0.0  ...    2710000.0    2712000.0
Finland           0.0           5316000.0  ...    4481000.0    4759000.0
                  1.0           6040000.0  ...   14608000.0   12832000.0
France            0.0           2410000.0  ...    3401000.0    3464000.0
                  1.0           2555000.0  ...    7622000.0    7677000.0
Germany           0.0           6487000.0  ...    3771000.0          0.0
                  1.0          34111000.0  ...   42497000.0   30665000.0
Greece            0.0            683000.0  ...    3324000.0    2526000.0
                  1.0           1128000.0  ...    2630000.0    3262000.0
Hungary           0.0            765000.0  ...    4092000.0    5786000.0
                  1.0           3584000.0  ...   12878000.0   10849000.0
Italy             0.0          21682000.0  ...   25297000.0   23341000.0
                  1.0          20856000.0  ...   20110000.0   20997000.0
Latvia            0.0            742000.0  ...    1280000.0    1382000.0
                  1.0           1855000.0  ...    3655000.0    3623000.0
Lithuania         0.0           1882000.0  ...    4831000.0    4447000.0
                  1.0           3011000.0  ...    3229000.0    3626000.0
Luxembourg        1.0           6212000.0  ...    6732098.0    6851524.0
Malta             1.0                 0.0  ...          0.0          0.0
Netherlands (the) 0.0              4000.0  ...    5645000.0    4172000.0
                  1.0          21172000.0  ...   26248000.0   28938000.0
Poland            0.0           1453000.0  ...    1005000.0    1029000.0
                  1.0           2038000.0  ...    8798000.0    6772000.0
Portugal          1.0           3628000.0  ...   10766000.0    8100000.0
Romania           0.0            879000.0  ...    1186000.0     816000.0
                  1.0            224000.0  ...    2717000.0    1921000.0
Slovakia          0.0                 0.0  ...      56000.0     173000.0
                  1.0           3738000.0  ...   13416000.0   10546000.0
Slovenia          0.0            438000.0  ...          0.0          0.0
                  1.0            158000.0  ...    7452000.0    7521000.0
Spain             0.0              8000.0  ...       5000.0       1000.0
                  1.0          11951000.0  ...    7782000.0    9886000.0
Sweden            0.0           5906000.0  ...    9955000.0    6904000.0
                  1.0           2550000.0  ...    1727000.0    5770000.0

                                                                     \
                                     2014         2015         2016
Country           Partner_EU
                              348960899.0  374320132.0  352559687.0
Austria           0.0            547904.0     269870.0     391281.0
                  1.0          26163819.0   29119293.0   25974879.0
Belgium           1.0          21791000.0   23714000.0   14648000.0
Bulgaria          0.0             86000.0     117000.0     231000.0
                  1.0           4233000.0    4134000.0    4337000.0
Croatia           0.0           2879000.0    5597000.0    6076000.0
                  1.0           8019000.0    7561000.0    6322000.0
Czechia           1.0          11842000.0   16146000.0   13817000.0
Denmark           0.0           4120000.0    6570759.0    6807449.0
                  1.0           8582000.0    9073988.0    8169009.0
Estonia           0.0                 0.0          0.0          0.0
                  1.0           3730000.0    5452000.0    3577000.0
Finland           0.0           3440000.0    4073000.0    6057000.0
                  1.0          18182000.0   17386000.0   16053000.0
France            0.0           2961000.0    4403000.0    5306000.0
                  1.0           4898000.0    5384000.0   13294000.0
Germany           0.0                 0.0          0.0          0.0
                  1.0          28587000.0   25623000.0   20687000.0
Greece            0.0           4642000.0    5866000.0    5277000.0
                  1.0           4819000.0    5215000.0    4556000.0
Hungary           0.0           5826000.0    6069000.0    5310000.0
                  1.0          13253000.0   13866000.0   12641000.0
Italy             0.0          24414000.0   26180000.0   20977000.0
                  1.0          22333000.0   24669000.0   22204000.0
Latvia            0.0           1290000.0    1325000.0    1106000.0
                  1.0           4050000.0    3921000.0    3722000.0
Lithuania         0.0           5504000.0    4456000.0    4384000.0
                  1.0           3017000.0    3482000.0    6722000.0
Luxembourg        1.0           6961176.0    7518755.0    7718393.0
Malta             1.0                 0.0    1054000.0    1526688.0
Netherlands (the) 0.0           5463000.0    5768428.0    4196992.0
                  1.0          27381000.0   24984039.0   19920996.0
Poland            0.0            686000.0      66000.0     957000.0
                  1.0          12822000.0   14393000.0   13060000.0
Portugal          1.0           7247000.0    8077000.0    4616000.0
Romania           0.0            664000.0     619000.0    1315000.0
                  1.0           2147000.0    3873000.0    2862000.0
Slovakia          0.0             62000.0      64000.0      64000.0
                  1.0          12902000.0   14935000.0   13185000.0
Slovenia          0.0                 0.0          0.0          0.0
                  1.0           7254000.0    9045000.0    8359000.0
Spain             0.0              2000.0      14000.0       8000.0
                  1.0          12308000.0   14942000.0   21837000.0
Sweden            0.0           9856000.0    7222000.0    9118000.0
                  1.0           3996000.0    2072000.0    5169000.0

                                                                       \
                                     2017          2018          2019
Country           Partner_EU
                              353152162.0  3.598576e+08  3.548831e+08
Austria           0.0            463061.0  1.200032e+06  1.610522e+06
                  1.0          28899366.0  2.687603e+07  2.443632e+07
Belgium           1.0          14189400.0  2.163430e+07  1.260800e+07
Bulgaria          0.0            113523.0  1.316324e+05  2.740670e+05
                  1.0           3591900.0  2.090699e+06  2.770880e+06
Croatia           0.0           3740200.0  7.762500e+06  3.185200e+06
                  1.0           8417700.0  4.930900e+06  8.215600e+06
Czechia           1.0          15071999.0  1.157341e+07  1.102621e+07
Denmark           0.0           5430795.0  5.034756e+06  3.383878e+06
                  1.0           9787314.0  1.059885e+07  1.259802e+07
Estonia           0.0                 0.0  0.000000e+00  0.000000e+00
                  1.0           2281000.0  3.053000e+06  4.861000e+06
Finland           0.0           6079000.0  8.040000e+06  7.839000e+06
                  1.0          16125000.0  1.450800e+07  1.609900e+07
France            0.0           6400180.0  4.159115e+06  4.581372e+06
                  1.0          12528000.0  8.966246e+06  1.034160e+07
Germany           0.0                 0.0  0.000000e+00  0.000000e+00
                  1.0          17938000.0  2.143500e+07  2.897600e+07
Greece            0.0           4996000.0  5.821000e+06  5.866000e+06
                  1.0           3700000.0  2.729000e+06  5.201000e+06
Hungary           0.0           4869000.0  6.280000e+06  4.510000e+06
                  1.0          14934000.0  1.233300e+07  1.534300e+07
Italy             0.0          21592196.0  2.254028e+07  2.223143e+07
                  1.0          21302685.0  2.462992e+07  2.174351e+07
Latvia            0.0            954789.0  1.203202e+06  1.095463e+06
                  1.0           3118123.0  3.970480e+06  3.515298e+06
Lithuania         0.0           4436900.0  5.037300e+06  5.971300e+06
                  1.0           7489300.0  7.810200e+06  7.296600e+06
Luxembourg        1.0           7566690.0  7.553012e+06  6.817520e+06
Malta             1.0            897066.0  6.312930e+05  6.567560e+05
Netherlands (the) 0.0           4980789.0  3.876972e+06  2.634024e+06
                  1.0          17286168.0  2.268923e+07  1.738430e+07
Poland            0.0            895000.0  1.410155e+06  1.376820e+06
                  1.0          12376000.0  1.240565e+07  1.649151e+07
Portugal          1.0           5505732.0  5.667568e+06  8.099208e+06
Romania           0.0           1241749.0  8.232560e+05  2.219436e+06
                  1.0           3600005.0  2.873338e+06  3.273197e+06
Slovakia          0.0              9000.0  1.700000e+05  3.000000e+04
                  1.0          15554000.0  1.225800e+07  1.350800e+07
Slovenia          0.0                 0.0  0.000000e+00  0.000000e+00
                  1.0           9132532.0  8.930239e+06  9.021273e+06
Spain             0.0              8000.0  1.800000e+05  1.207714e+06
                  1.0          23754000.0  2.383800e+07  1.751311e+07

In [51]:
pivot_countries = pd.pivot_table(data=EU_Totals, index=['Country'],
                      values=['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL'],
                      aggfunc=['sum'])
pivot_countries

                           sum                                         \
                          1990         1991         1992         1993
Country
                   161490000.0  142371000.0  151939000.0  171452000.0
Austria              6839000.0    8503000.0    9175000.0    8072000.0
Belgium              4785000.0    4998000.0    5849000.0    7590000.0
Bulgaria                   0.0          0.0     329000.0      16000.0
Croatia                    0.0          0.0          0.0    2391000.0
Czechia              8179000.0    7194000.0    6156000.0    5952000.0
Denmark             11973000.0    3075000.0    8647000.0    6279000.0
Estonia                    0.0          0.0          0.0     221000.0
Finland             11007000.0    7931000.0    9067000.0    8013000.0
France               6629000.0    5516000.0    4737000.0    3663000.0
Germany             25127000.0   30416000.0   28418000.0   33628000.0
Greece               1330000.0    1498000.0     967000.0    1093000.0
Hungary             13299000.0    8410000.0    4988000.0    4093000.0
Italy               35577000.0   35454000.0   35947000.0   40109000.0
Latvia                     0.0          0.0          0.0    2672000.0
Lithuania            4538000.0    3725000.0    5338000.0    5736000.0
Luxembourg           4678000.0    4853000.0    4511000.0    4445000.0
Malta                      0.0          0.0          0.0          0.0
Netherlands (the)    9679000.0    9778000.0    8906000.0   10572000.0
Poland                     0.0          0.0          0.0    5600000.0
Portugal             1733000.0    1712000.0    2538000.0    2077000.0
Romania                    0.0          0.0    2839000.0    1643000.0
Slovakia                   0.0          0.0          0.0    4297000.0
Slovenia                   0.0          0.0     329000.0     706000.0
Spain                3208000.0    3083000.0    4351000.0    4606000.0
Sweden              12909000.0    6225000.0    8847000.0    7978000.0

                                                                       \
                          1994         1995         1996         1997
Country
                   163993000.0  176841000.0  188697000.0  192988000.0
Austria              8219000.0    7287000.0    9428000.0    9008000.0
Belgium              9053000.0    9398000.0    9637000.0    9975000.0
Bulgaria                   0.0     102000.0          0.0     574000.0
Croatia              2455000.0    2548000.0    3227000.0    3355000.0
Czechia              5415000.0    6722000.0    8811000.0    9013000.0
Denmark              1781000.0    4013000.0    3781000.0    3796000.0
Estonia               315000.0     245000.0     240000.0     210000.0
Finland              7171000.0    8501000.0    5367000.0    8103000.0
France               3718000.0    2834000.0    3614000.0    4238000.0
Germany             35908000.0   39735000.0   37404000.0   38012000.0
Greece                816000.0    1390000.0    2664000.0    3003000.0
Hungary              2954000.0    3210000.0    3473000.0    4410000.0
Italy               38695000.0   38662000.0   38149000.0   39827000.0
Latvia               2648000.0    2647000.0    3438000.0    1824000.0
Lithuania            7114000.0    5270000.0    4182000.0    4524000.0
Luxembourg           5019000.0    5746000.0    5712000.0    6032000.0
Malta                      0.0          0.0          0.0          0.0
Netherlands (the)   10850000.0   11979000.0   11288000.0   13107000.0
Poland               4563000.0    4356000.0    4801000.0    5357000.0
Portugal             2257000.0    2655000.0    4116000.0    5376000.0
Romania                    0.0          0.0          0.0     777000.0
Slovakia             2807000.0    3448000.0    5875000.0    6798000.0
Slovenia              448000.0     740000.0     855000.0     820000.0
Spain                5106000.0    7633000.0    6750000.0    4597000.0
Sweden               6681000.0    7720000.0   15885000.0   10252000.0

                                             ...                            \
                          1998         1999  ...         2012         2013
Country                                      ...
                   183961000.0  211106000.0  ...  346173813.0  318233094.0
Austria             10304000.0   11608000.0  ...   23429715.0   24959570.0
Belgium              7828000.0    9059000.0  ...   16848000.0   17243000.0
Bulgaria              564000.0    1670000.0  ...    2353000.0    3351000.0
Croatia                    0.0    1219000.0  ...   13174000.0   11260000.0
Czechia              8383000.0    8983000.0  ...   10543000.0    8612000.0
Denmark              3280000.0    4963000.0  ...   15920000.0   11459000.0
Estonia               138000.0     138000.0  ...    2710000.0    2712000.0
Finland              9582000.0   11356000.0  ...   19089000.0   17591000.0
France               4558000.0    4965000.0  ...   11023000.0   11141000.0
Germany             38315000.0   40598000.0  ...   46268000.0   30665000.0
Greece               2500000.0    1811000.0  ...    5954000.0    5788000.0
Hungary              3354000.0    4349000.0  ...   16970000.0   16635000.0
Italy               41633000.0   42538000.0  ...   45407000.0   44338000.0
Latvia                914000.0    2597000.0  ...    4935000.0    5005000.0
Lithuania            4572000.0    4893000.0  ...    8060000.0    8073000.0
Luxembourg           6338000.0    6212000.0  ...    6732098.0    6851524.0
Malta                      0.0          0.0  ...          0.0          0.0
Netherlands (the)   12234000.0   21176000.0  ...   31893000.0   33110000.0
Poland               4608000.0    3491000.0  ...    9803000.0    7801000.0
Portugal             3974000.0    3628000.0  ...   10766000.0    8100000.0
Romania               724000.0    1103000.0  ...    3903000.0    2737000.0
Slovakia             4381000.0    3738000.0  ...   13472000.0   10719000.0
Slovenia              711000.0     596000.0  ...    7452000.0    7521000.0
Spain                8964000.0   11959000.0  ...    7787000.0    9887000.0
Sweden               6102000.0    8456000.0  ...   11682000.0   12674000.0

                                                                       \
                          2014         2015         2016         2017
Country
                   348960899.0  374320132.0  352559687.0  353152162.0
Austria             26711723.0   29389163.0   26366160.0   29362427.0
Belgium             21791000.0   23714000.0   14648000.0   14189400.0
Bulgaria             4319000.0    4251000.0    4568000.0    3705423.0
Croatia             10898000.0   13158000.0   12398000.0   12157900.0
Czechia             11842000.0   16146000.0   13817000.0   15071999.0
Denmark             12702000.0   15644747.0   14976458.0   15218109.0
Estonia              3730000.0    5452000.0    3577000.0    2281000.0
Finland             21622000.0   21459000.0   22110000.0   22204000.0
France               7859000.0    9787000.0   18600000.0   18928180.0
Germany             28587000.0   25623000.0   20687000.0   17938000.0
Greece               9461000.0   11081000.0    9833000.0    8696000.0
Hungary             19079000.0   19935000.0   17951000.0   19803000.0
Italy               46747000.0   50849000.0   43181000.0   42894881.0
Latvia               5340000.0    5246000.0    4828000.0    4072912.0
Lithuania            8521000.0    7938000.0   11106000.0   11926200.0
Luxembourg           6961176.0    7518755.0    7718393.0    7566690.0
Malta                      0.0    1054000.0    1526688.0     897066.0
Netherlands (the)   32844000.0   30752467.0   24117988.0   22266957.0
Poland              13508000.0   14459000.0   14017000.0   13271000.0
Portugal             7247000.0    8077000.0    4616000.0    5505732.0
Romania              2811000.0    4492000.0    4177000.0    4841754.0
Slovakia            12964000.0   14999000.0   13249000.0   15563000.0
Slovenia             7254000.0    9045000.0    8359000.0    9132532.0
Spain               12310000.0   14956000.0   21845000.0   23762000.0
Sweden              13852000.0    9294000.0   14287000.0   11896000.0


                           2018          2019          2020         TOTAL
Country
                   3.598576e+08  3.548831e+08  3.595373e+08  8.353468e+09
Austria            2.807606e+07  2.604685e+07  2.452249e+07  5.538912e+08
Belgium            2.163430e+07  1.260800e+07  1.323520e+07  4.086599e+08
Bulgaria           2.222331e+06  3.044947e+06  3.706736e+06  5.426744e+07
Croatia            1.269340e+07  1.140080e+07  1.049100e+07  1.968261e+08
Czechia            1.157341e+07  1.102621e+07  1.336805e+07  2.909937e+08
Denmark            1.563361e+07  1.598190e+07  1.859397e+07  3.054218e+08
Estonia            3.053000e+06  4.861000e+06  7.367000e+06  4.709700e+07
Finland            2.254800e+07  2.393800e+07  2.164700e+07  4.517210e+08
France             1.312536e+07  1.492297e+07  1.790631e+07  2.602028e+08
Germany            2.143500e+07  2.897600e+07  3.092700e+07  1.164019e+09
Greece             8.550000e+06  1.106700e+07  9.831000e+06  1.652890e+08
Hungary            1.861300e+07  1.985300e+07  1.917600e+07  3.717040e+08
Italy              4.717020e+07  4.397494e+07  3.978994e+07  1.363931e+09
Latvia             5.173682e+06  4.610761e+06  4.173365e+06  1.003277e+08
Lithuania          1.284750e+07  1.326790e+07  1.201340e+07  2.101970e+08
Luxembourg         7.553012e+06  6.817520e+06  6.543493e+06  1.974092e+08
Malta              6.312930e+05  6.567560e+05  4.198100e+05  5.185613e+06
Netherlands (the)  2.656620e+07  2.001832e+07  1.923240e+07  6.142703e+08
Poland             1.381580e+07  1.786833e+07  2.062412e+07  2.273842e+08
Portugal           5.667568e+06  8.099208e+06  7.553113e+06  1.827646e+08
Romania            3.696594e+06  5.492633e+06  8.251648e+06  6.333563e+07
Slovakia           1.242800e+07  1.353800e+07  1.328900e+07  2.547870e+08
Slovenia           8.930239e+06  9.021273e+06  7.119950e+06  1.564340e+08
Spain              2.401800e+07  1.872083e+07  1.792835e+07  3.178992e+08
Sweden             1.220200e+07  9.070000e+06  1.182700e+07  3.894500e+08

[26 rows x 32 columns]

In [52]:
EU_Totals

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
9,ES,Spain,1.0,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.500000e-02,1.600000e-02,3.100000e-02
11,FR,France,1.0,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2.100000e-02,2.100000e-02
89,EL,Greece,1.0,AL,Albania,0.0,E7000,GWH,165000.0,416000.0,...,17000.0,1380000.0,105000.0,332000.0,822000.0,80000.0,1.062000e+06,4.750000e+05,6.220000e+05,8.039000e+06
274,CZ,Czechia,1.0,AT,Austria,1.0,E7000,GWH,34000.0,221000.0,...,0.0,0.0,265000.0,41000.0,136000.0,62478.0,1.125610e+05,1.447620e+05,3.784200e+05,2.085221e+06
275,DE,Germany,1.0,AT,Austria,1.0,E7000,GWH,4092000.0,4367000.0,...,8221000.0,8842000.0,7144000.0,7071000.0,5979000.0,4008000.0,4.793000e+06,4.876000e+06,6.101000e+06,1.842300e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4144,HU,Hungary,1.0,UA,Ukraine,0.0,E7000,GWH,12160000.0,6605000.0,...,4014000.0,4836000.0,5614000.0,5550000.0,4412000.0,4563000.0,5.054000e+06,4.014000e+06,2.484000e+06,1.108490e+08
4152,PL,Poland,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,1005000.0,1029000.0,686000.0,66000.0,957000.0,895000.0,1.410155e+06,1.376820e+06,1.484123e+06,2.028710e+07
4154,RO,Romania,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,524000.0,64000.0,122000.0,172000.0,29000.0,473077.0,7.331500e+04,5.010610e+05,5.838480e+05,5.393301e+06
4157,SK,Slovakia,1.0,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,56000.0,173000.0,62000.0,64000.0,64000.0,9000.0,1.700000e+05,3.000000e+04,9.300000e+04,9.433000e+06
GRAND TOTAL,,,,,,,,,161490000.0,142371000.0,...,346173813.0,318233094.0,348960899.0,374320132.0,352559687.0,353152162.0,3.598576e+08,3.548831e+08,3.595373e+08,8.353468e+09

In [53]:
EU_Totals['EU?']=EU_Totals['EU?'].astype(bool)
EU_Totals

,Alpha_2_code,Country,EU?,partner,Partner_country,Partner_EU,siec,unit,1990,1991,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,TOTAL
9,ES,Spain,True,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.500000e-02,1.600000e-02,3.100000e-02
11,FR,France,True,AD,Andorra,0.0,E7000,GWH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,2.100000e-02,2.100000e-02
89,EL,Greece,True,AL,Albania,0.0,E7000,GWH,165000.0,416000.0,...,17000.0,1380000.0,105000.0,332000.0,822000.0,80000.0,1.062000e+06,4.750000e+05,6.220000e+05,8.039000e+06
274,CZ,Czechia,True,AT,Austria,1.0,E7000,GWH,34000.0,221000.0,...,0.0,0.0,265000.0,41000.0,136000.0,62478.0,1.125610e+05,1.447620e+05,3.784200e+05,2.085221e+06
275,DE,Germany,True,AT,Austria,1.0,E7000,GWH,4092000.0,4367000.0,...,8221000.0,8842000.0,7144000.0,7071000.0,5979000.0,4008000.0,4.793000e+06,4.876000e+06,6.101000e+06,1.842300e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4144,HU,Hungary,True,UA,Ukraine,0.0,E7000,GWH,12160000.0,6605000.0,...,4014000.0,4836000.0,5614000.0,5550000.0,4412000.0,4563000.0,5.054000e+06,4.014000e+06,2.484000e+06,1.108490e+08
4152,PL,Poland,True,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,1005000.0,1029000.0,686000.0,66000.0,957000.0,895000.0,1.410155e+06,1.376820e+06,1.484123e+06,2.028710e+07
4154,RO,Romania,True,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,524000.0,64000.0,122000.0,172000.0,29000.0,473077.0,7.331500e+04,5.010610e+05,5.838480e+05,5.393301e+06
4157,SK,Slovakia,True,UA,Ukraine,0.0,E7000,GWH,0.0,0.0,...,56000.0,173000.0,62000.0,64000.0,64000.0,9000.0,1.700000e+05,3.000000e+04,9.300000e+04,9.433000e+06
GRAND TOTAL,,,False,,,,,,161490000.0,142371000.0,...,346173813.0,318233094.0,348960899.0,374320132.0,352559687.0,353152162.0,3.598576e+08,3.548831e+08,3.595373e+08,8.353468e+09

In [77]:
import numpy as np
EU_subtotals = pd.pivot_table(EU_Totals, values = ['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
                             '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
                             '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
                             '2020', 'TOTAL'],
                              index=['Country'], columns=['EU?'], aggfunc=np.sum, margins=True)

EU_subtotals.stack()

                                1990         1991         1992         1993  \
Country           EU?
                  False  161490000.0  142371000.0  151939000.0  171452000.0
                  All    161490000.0  142371000.0  151939000.0  171452000.0
Austria           True     6839000.0    8503000.0    9175000.0    8072000.0
                  All      6839000.0    8503000.0    9175000.0    8072000.0
Belgium           True     4785000.0    4998000.0    5849000.0    7590000.0
                  All      4785000.0    4998000.0    5849000.0    7590000.0
Bulgaria          True           0.0          0.0     329000.0      16000.0
                  All            0.0          0.0     329000.0      16000.0
Croatia           True           0.0          0.0          0.0    2391000.0
                  All            0.0          0.0          0.0    2391000.0
Czechia           True     8179000.0    7194000.0    6156000.0    5952000.0
                  All      8179000.0    7194000.0    6156000.0    5952000.0
Denmark           True    11973000.0    3075000.0    8647000.0    6279000.0
                  All     11973000.0    3075000.0    8647000.0    6279000.0
Estonia           True           0.0          0.0          0.0     221000.0
                  All            0.0          0.0          0.0     221000.0
Finland           True    11007000.0    7931000.0    9067000.0    8013000.0
                  All     11007000.0    7931000.0    9067000.0    8013000.0
France            True     6629000.0    5516000.0    4737000.0    3663000.0
                  All      6629000.0    5516000.0    4737000.0    3663000.0
Germany           True    25127000.0   30416000.0   28418000.0   33628000.0
                  All     25127000.0   30416000.0   28418000.0   33628000.0
Greece            True     1330000.0    1498000.0     967000.0    1093000.0
                  All      1330000.0    1498000.0     967000.0    1093000.0
Hungary           True    13299000.0    8410000.0    4988000.0    4093000.0
                  All     13299000.0    8410000.0    4988000.0    4093000.0
Italy             True    35577000.0   35454000.0   35947000.0   40109000.0
                  All     35577000.0   35454000.0   35947000.0   40109000.0
Latvia            True           0.0          0.0          0.0    2672000.0
                  All            0.0          0.0          0.0    2672000.0
Lithuania         True     4538000.0    3725000.0    5338000.0    5736000.0
                  All      4538000.0    3725000.0    5338000.0    5736000.0
Luxembourg        True     4678000.0    4853000.0    4511000.0    4445000.0
                  All      4678000.0    4853000.0    4511000.0    4445000.0
Malta             True           0.0          0.0          0.0          0.0
                  All            0.0          0.0          0.0          0.0
Netherlands (the) True     9679000.0    9778000.0    8906000.0   10572000.0
                  All      9679000.0    9778000.0    8906000.0   10572000.0
Poland            True           0.0          0.0          0.0    5600000.0
                  All            0.0          0.0          0.0    5600000.0
Portugal          True     1733000.0    1712000.0    2538000.0    2077000.0
                  All      1733000.0    1712000.0    2538000.0    2077000.0
Romania           True           0.0          0.0    2839000.0    1643000.0
                  All            0.0          0.0    2839000.0    1643000.0
Slovakia          True           0.0          0.0          0.0    4297000.0
                  All            0.0          0.0          0.0    4297000.0
Slovenia          True           0.0          0.0     329000.0     706000.0
                  All            0.0          0.0     329000.0     706000.0
Spain             True     3208000.0    3083000.0    4351000.0    4606000.0
                  All      3208000.0    3083000.0    4351000.0    4606000.0
Sweden            True    12909000.0    6225000.0    8847000.0    7978000.0
                  All     12909000.0    6225000.0    8847000.0    7978000.0
All               False  161490000.0  142371000.0  151939000.0  171452000.0
                  True   161490000.0  142371000.0  151939000.0  171452000.0
                  All    322980000.0  284742000.0  303878000.0  342904000.0

                                1994         1995         1996         1997  \
Country           EU?
                  False  163993000.0  176841000.0  188697000.0  192988000.0
                  All    163993000.0  176841000.0  188697000.0  192988000.0
Austria           True     8219000.0    7287000.0    9428000.0    9008000.0
                  All      8219000.0    7287000.0    9428000.0    9008000.0
Belgium           True     9053000.0    9398000.0    9637000.0    9975000.0
                  All      9053000.0    9398000.0    9637000.0    9975000.0
Bulgaria          True           0.0     102000.0          0.0     574000.0
                  All            0.0     102000.0          0.0     574000.0
Croatia           True     2455000.0    2548000.0    3227000.0    3355000.0
                  All      2455000.0    2548000.0    3227000.0    3355000.0
Czechia           True     5415000.0    6722000.0    8811000.0    9013000.0
                  All      5415000.0    6722000.0    8811000.0    9013000.0
Denmark           True     1781000.0    4013000.0    3781000.0    3796000.0
                  All      1781000.0    4013000.0    3781000.0    3796000.0
Estonia           True      315000.0     245000.0     240000.0     210000.0
                  All       315000.0     245000.0     240000.0     210000.0
Finland           True     7171000.0    8501000.0    5367000.0    8103000.0
                  All      7171000.0    8501000.0    5367000.0    8103000.0
France            True     3718000.0    2834000.0    3614000.0    4238000.0
                  All      3718000.0    2834000.0    3614000.0    4238000.0
Germany           True    35908000.0   39735000.0   37404000.0   38012000.0
                  All     35908000.0   39735000.0   37404000.0   38012000.0
Greece            True      816000.0    1390000.0    2664000.0    3003000.0
                  All       816000.0    1390000.0    2664000.0    3003000.0
Hungary           True     2954000.0    3210000.0    3473000.0    4410000.0
                  All      2954000.0    3210000.0    3473000.0    4410000.0
Italy             True    38695000.0   38662000.0   38149000.0   39827000.0
                  All     38695000.0   38662000.0   38149000.0   39827000.0
Latvia            True     2648000.0    2647000.0    3438000.0    1824000.0
                  All      2648000.0    2647000.0    3438000.0    1824000.0
Lithuania         True     7114000.0    5270000.0    4182000.0    4524000.0
                  All      7114000.0    5270000.0    4182000.0    4524000.0
Luxembourg        True     5019000.0    5746000.0    5712000.0    6032000.0
                  All      5019000.0    5746000.0    5712000.0    6032000.0
Malta             True           0.0          0.0          0.0          0.0
                  All            0.0          0.0          0.0          0.0
Netherlands (the) True    10850000.0   11979000.0   11288000.0   13107000.0
                  All     10850000.0   11979000.0   11288000.0   13107000.0
Poland            True     4563000.0    4356000.0    4801000.0    5357000.0
                  All      4563000.0    4356000.0    4801000.0    5357000.0
Portugal          True     2257000.0    2655000.0    4116000.0    5376000.0
                  All      2257000.0    2655000.0    4116000.0    5376000.0
Romania           True           0.0          0.0          0.0     777000.0
                  All            0.0          0.0          0.0     777000.0
Slovakia          True     2807000.0    3448000.0    5875000.0    6798000.0
                  All      2807000.0    3448000.0    5875000.0    6798000.0
Slovenia          True      448000.0     740000.0     855000.0     820000.0
                  All       448000.0     740000.0     855000.0     820000.0
Spain             True     5106000.0    7633000.0    6750000.0    4597000.0
                  All      5106000.0    7633000.0    6750000.0    4597000.0
Sweden            True     6681000.0    7720000.0   15885000.0   10252000.0
                  All      6681000.0    7720000.0   15885000.0   10252000.0
All               False  163993000.0  176841000.0  188697000.0  192988000.0
                  True   163993000.0  176841000.0  188697000.0  192988000.0
                  All    327986000.0  353682000.0  377394000.0  385976000.0

                                1998         1999  ...         2012  \
Country           EU?                              ...
                  False  183961000.0  211106000.0  ...  346173813.0
                  All    183961000.0  211106000.0  ...  346173813.0
Austria           True    10304000.0   11608000.0  ...   23429715.0
                  All     10304000.0   11608000.0  ...   23429715.0
Belgium           True     7828000.0    9059000.0  ...   16848000.0
                  All      7828000.0    9059000.0  ...   16848000.0
Bulgaria          True      564000.0    1670000.0  ...    2353000.0
                  All       564000.0    1670000.0  ...    2353000.0
Croatia           True           0.0    1219000.0  ...   13174000.0
                  All            0.0    1219000.0  ...   13174000.0
Czechia           True     8383000.0    8983000.0  ...   10543000.0
                  All      8383000.0    8983000.0  ...   10543000.0
Denmark           True     3280000.0    4963000.0  ...   15920000.0
                  All      3280000.0    4963000.0  ...   15920000.0
Estonia           True      138000.0     138000.0  ...    2710000.0
                  All       138000.0     138000.0  ...    2710000.0
Finland           True     9582000.0   11356000.0  ...   19089000.0
                  All      9582000.0   11356000.0  ...   19089000.0
France            True     4558000.0    4965000.0  ...   11023000.0
                  All      4558000.0    4965000.0  ...   11023000.0
Germany           True    38315000.0   40598000.0  ...   46268000.0
                  All     38315000.0   40598000.0  ...   46268000.0
Greece            True     2500000.0    1811000.0  ...    5954000.0
                  All      2500000.0    1811000.0  ...    5954000.0
Hungary           True     3354000.0    4349000.0  ...   16970000.0
                  All      3354000.0    4349000.0  ...   16970000.0
Italy             True    41633000.0   42538000.0  ...   45407000.0
                  All     41633000.0   42538000.0  ...   45407000.0
Latvia            True      914000.0    2597000.0  ...    4935000.0
                  All       914000.0    2597000.0  ...    4935000.0
Lithuania         True     4572000.0    4893000.0  ...    8060000.0
                  All      4572000.0    4893000.0  ...    8060000.0
Luxembourg        True     6338000.0    6212000.0  ...    6732098.0
                  All      6338000.0    6212000.0  ...    6732098.0
Malta             True           0.0          0.0  ...          0.0
                  All            0.0          0.0  ...          0.0
Netherlands (the) True    12234000.0   21176000.0  ...   31893000.0
                  All     12234000.0   21176000.0  ...   31893000.0
Poland            True     4608000.0    3491000.0  ...    9803000.0
                  All      4608000.0    3491000.0  ...    9803000.0
Portugal          True     3974000.0    3628000.0  ...   10766000.0
                  All      3974000.0    3628000.0  ...   10766000.0
Romania           True      724000.0    1103000.0  ...    3903000.0
                  All       724000.0    1103000.0  ...    3903000.0
Slovakia          True     4381000.0    3738000.0  ...   13472000.0
                  All      4381000.0    3738000.0  ...   13472000.0
Slovenia          True      711000.0     596000.0  ...    7452000.0
                  All       711000.0     596000.0  ...    7452000.0
Spain             True     8964000.0   11959000.0  ...    7787000.0
                  All      8964000.0   11959000.0  ...    7787000.0
Sweden            True     6102000.0    8456000.0  ...   11682000.0
                  All      6102000.0    8456000.0  ...   11682000.0
All               False  183961000.0  211106000.0  ...  346173813.0
                  True   183961000.0  211106000.0  ...  346173813.0
                  All    367922000.0  422212000.0  ...  692347626.0

                                2013         2014         2015         2016  \
Country           EU?
                  False  318233094.0  348960899.0  374320132.0  352559687.0
                  All    318233094.0  348960899.0  374320132.0  352559687.0
Austria           True    24959570.0   26711723.0   29389163.0   26366160.0
                  All     24959570.0   26711723.0   29389163.0   26366160.0
Belgium           True    17243000.0   21791000.0   23714000.0   14648000.0
                  All     17243000.0   21791000.0   23714000.0   14648000.0
Bulgaria          True     3351000.0    4319000.0    4251000.0    4568000.0
                  All      3351000.0    4319000.0    4251000.0    4568000.0
Croatia           True    11260000.0   10898000.0   13158000.0   12398000.0
                  All     11260000.0   10898000.0   13158000.0   12398000.0
Czechia           True     8612000.0   11842000.0   16146000.0   13817000.0
                  All      8612000.0   11842000.0   16146000.0   13817000.0
Denmark           True    11459000.0   12702000.0   15644747.0   14976458.0
                  All     11459000.0   12702000.0   15644747.0   14976458.0
Estonia           True     2712000.0    3730000.0    5452000.0    3577000.0
                  All      2712000.0    3730000.0    5452000.0    3577000.0
Finland           True    17591000.0   21622000.0   21459000.0   22110000.0
                  All     17591000.0   21622000.0   21459000.0   22110000.0
France            True    11141000.0    7859000.0    9787000.0   18600000.0
                  All     11141000.0    7859000.0    9787000.0   18600000.0
Germany           True    30665000.0   28587000.0   25623000.0   20687000.0
                  All     30665000.0   28587000.0   25623000.0   20687000.0
Greece            True     5788000.0    9461000.0   11081000.0    9833000.0
                  All      5788000.0    9461000.0   11081000.0    9833000.0
Hungary           True    16635000.0   19079000.0   19935000.0   17951000.0
                  All     16635000.0   19079000.0   19935000.0   17951000.0
Italy             True    44338000.0   46747000.0   50849000.0   43181000.0
                  All     44338000.0   46747000.0   50849000.0   43181000.0
Latvia            True     5005000.0    5340000.0    5246000.0    4828000.0
                  All      5005000.0    5340000.0    5246000.0    4828000.0
Lithuania         True     8073000.0    8521000.0    7938000.0   11106000.0
                  All      8073000.0    8521000.0    7938000.0   11106000.0
Luxembourg        True     6851524.0    6961176.0    7518755.0    7718393.0
                  All      6851524.0    6961176.0    7518755.0    7718393.0
Malta             True           0.0          0.0    1054000.0    1526688.0
                  All            0.0          0.0    1054000.0    1526688.0
Netherlands (the) True    33110000.0   32844000.0   30752467.0   24117988.0
                  All     33110000.0   32844000.0   30752467.0   24117988.0
Poland            True     7801000.0   13508000.0   14459000.0   14017000.0
                  All      7801000.0   13508000.0   14459000.0   14017000.0
Portugal          True     8100000.0    7247000.0    8077000.0    4616000.0
                  All      8100000.0    7247000.0    8077000.0    4616000.0
Romania           True     2737000.0    2811000.0    4492000.0    4177000.0
                  All      2737000.0    2811000.0    4492000.0    4177000.0
Slovakia          True    10719000.0   12964000.0   14999000.0   13249000.0
                  All     10719000.0   12964000.0   14999000.0   13249000.0
Slovenia          True     7521000.0    7254000.0    9045000.0    8359000.0
                  All      7521000.0    7254000.0    9045000.0    8359000.0
Spain             True     9887000.0   12310000.0   14956000.0   21845000.0
                  All      9887000.0   12310000.0   14956000.0   21845000.0
Sweden            True    12674000.0   13852000.0    9294000.0   14287000.0
                  All     12674000.0   13852000.0    9294000.0   14287000.0
All               False  318233094.0  348960899.0  374320132.0  352559687.0
                  True   318233094.0  348960899.0  374320132.0  352559687.0
                  All    636466188.0  697921798.0  748640264.0  705119374.0

                                2017          2018          2019  \
Country           EU?
                  False  353152162.0  3.598576e+08  3.548831e+08
                  All    353152162.0  3.598576e+08  3.548831e+08
Austria           True    29362427.0  2.807606e+07  2.604685e+07
                  All     29362427.0  2.807606e+07  2.604685e+07
Belgium           True    14189400.0  2.163430e+07  1.260800e+07
                  All     14189400.0  2.163430e+07  1.260800e+07
Bulgaria          True     3705423.0  2.222331e+06  3.044947e+06
                  All      3705423.0  2.222331e+06  3.044947e+06
Croatia           True    12157900.0  1.269340e+07  1.140080e+07
                  All     12157900.0  1.269340e+07  1.140080e+07
Czechia           True    15071999.0  1.157341e+07  1.102621e+07
                  All     15071999.0  1.157341e+07  1.102621e+07
Denmark           True    15218109.0  1.563361e+07  1.598190e+07
                  All     15218109.0  1.563361e+07  1.598190e+07
Estonia           True     2281000.0  3.053000e+06  4.861000e+06
                  All      2281000.0  3.053000e+06  4.861000e+06
Finland           True    22204000.0  2.254800e+07  2.393800e+07
                  All     22204000.0  2.254800e+07  2.393800e+07
France            True    18928180.0  1.312536e+07  1.492297e+07
                  All     18928180.0  1.312536e+07  1.492297e+07
Germany           True    17938000.0  2.143500e+07  2.897600e+07
                  All     17938000.0  2.143500e+07  2.897600e+07
Greece            True     8696000.0  8.550000e+06  1.106700e+07
                  All      8696000.0  8.550000e+06  1.106700e+07
Hungary           True    19803000.0  1.861300e+07  1.985300e+07
                  All     19803000.0  1.861300e+07  1.985300e+07
Italy             True    42894881.0  4.717020e+07  4.397494e+07
                  All     42894881.0  4.717020e+07  4.397494e+07
Latvia            True     4072912.0  5.173682e+06  4.610761e+06
                  All      4072912.0  5.173682e+06  4.610761e+06
Lithuania         True    11926200.0  1.284750e+07  1.326790e+07
                  All     11926200.0  1.284750e+07  1.326790e+07
Luxembourg        True     7566690.0  7.553012e+06  6.817520e+06
                  All      7566690.0  7.553012e+06  6.817520e+06
Malta             True      897066.0  6.312930e+05  6.567560e+05
                  All       897066.0  6.312930e+05  6.567560e+05
Netherlands (the) True    22266957.0  2.656620e+07  2.001832e+07
                  All     22266957.0  2.656620e+07  2.001832e+07
Poland            True    13271000.0  1.381580e+07  1.786833e+07
                  All     13271000.0  1.381580e+07  1.786833e+07
Portugal          True     5505732.0  5.667568e+06  8.099208e+06
                  All      5505732.0  5.667568e+06  8.099208e+06
Romania           True     4841754.0  3.696594e+06  5.492633e+06
                  All      4841754.0  3.696594e+06  5.492633e+06
Slovakia          True    15563000.0  1.242800e+07  1.353800e+07
                  All     15563000.0  1.242800e+07  1.353800e+07
Slovenia          True     9132532.0  8.930239e+06  9.021273e+06
                  All      9132532.0  8.930239e+06  9.021273e+06
Spain             True    23762000.0  2.401800e+07  1.872083e+07